apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lwwebapphelm1
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/singsachin1709/agrocd_training.git
    path: myHelmCharts/lwchart
    targetRevision: main
