apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lwwebappprod
spec:
  project: default
  destination:
    server: https://192.168.76.2:8443 
    namespace: default
  source:
    repoURL: https://github.com/singsachin1709/agrocd_training.git
    path: multienv/prod
    targetRevision: main
